# --- State definitions for demo bot ---
(
    SELECTING_ACTION, ASK_RESUME, ASK_SEARCH_METHOD, ASK_COUNTRY, ASK_REGION, ASK_SCHEDULE,
    ASK_EMPLOYMENT, ASK_PROFESSION, ASK_KEYWORD, ASK_SEARCH_FIELD,
    ASK_COVER_LETTER, CONFIRMATION, ASK_PROFESSION_PAGE,
    # Cover Letter states
    COVER_LETTER_MENU, CL_ASK_TITLE, CL_ASK_BODY, CL_VIEW, CL_SAVE_BODY,
    ASK_HH_URL,
    # Auto-response states
    AUTO_RESPONSE_MAIN, AUTO_RESPONSE_SETUP, AUTO_RESPONSE_RESUME, AUTO_RESPONSE_SEARCH_METHOD,
    AUTO_RESPONSE_FILTERS, AUTO_RESPONSE_HH_URL, AUTO_RESPONSE_COVER_LETTER, AUTO_RESPONSE_CONFIRMATION,
    AUTO_RESPONSE_ACTIVE, AUTO_RESPONSE_STATS,
    # Stats states
    STATS_SELECT_RESUME, STATS_SHOW_RESUME_STATS,
    ASK_WORK_FORMAT 
) = range(32)